# Generated by Django 3.1.6 on 2021-03-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AutoPop', '0003_shopservice_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopservice',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
