# Generated by Django 3.1.6 on 2021-04-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210404_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopservice',
            name='home_service',
            field=models.BooleanField(default=False),
        ),
    ]
