# Generated by Django 3.1.6 on 2021-04-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_shopservice_home_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slogan',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
