# Generated by Django 3.1.6 on 2021-04-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210415_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='city',
            field=models.CharField(blank=True, default='Popayan', max_length=1023, null=True, verbose_name='City'),
        ),
    ]
