# Generated by Django 3.1.6 on 2021-04-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_shop_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customer',
            name='fullname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='fullname',
            field=models.CharField(default='', max_length=150),
        ),
    ]
