# Generated by Django 3.1.6 on 2021-04-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_serviceprovider_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopservice',
            name='service_name',
            field=models.CharField(default='NEW SERVICE', max_length=100),
        ),
    ]
