# Generated by Django 3.1.6 on 2021-04-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_shopservice_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopservice',
            name='long_description',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
