# Generated by Django 3.1.6 on 2021-04-24 20:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_shopservice_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEN', 'PENDING'), ('ACC', 'ACCEPTED'), ('CAN', 'CANCELED'), ('REJ', 'REJECTED'), ('COM', 'COMPLETED')], default='PEN', max_length=30)),
                ('review', models.CharField(default='', max_length=300)),
                ('rating', models.IntegerField(default=0, verbose_name='Rating')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.shopservice')),
            ],
        ),
    ]
