# Generated by Django 3.1.6 on 2021-04-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='review',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
