# Generated by Django 3.1.6 on 2021-04-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210425_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Mobile phone'),
        ),
    ]
