# Generated by Django 3.1.6 on 2021-04-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_customer_mobile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='location',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
