# Generated by Django 3.1.6 on 2021-04-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20210429_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('PEN', 'PENDING'), ('UN', 'UNPAID'), ('PA', 'PAID'), ('ACC', 'ACCEPTED'), ('CAN', 'CANCELED'), ('REJ', 'REJECTED'), ('COM', 'COMPLETED')], default='UN', max_length=30),
        ),
    ]
