name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit test
      run: |
        pip3 install --user django
        pip3 install django-cors-headers
        pip3 install dj-database-url
        pip3 install djangorestframework
        pip3 install django-widget-tweaks
        pip3 install django-countries

        python3 manage.py test